name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
      - name: Give execute permissions to gradlew
        run: chmod +x ./gradlew
      - name: Build and Test with Gradle Wrapper using Test Profile
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVICE_CLOUDFLARE_R2_URL: ${{ secrets.SERVICE_CLOUDFLARE_R2_URL }}
        run: ./gradlew build -Dspring.profiles.active=test